language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  
before_script:
  - composer install --dev
  - cd tests
script: 
  - ../vendor/bin/phpunit -v
after_script:
  - cd ..
  - travis_retry vendor/bin/php-coveralls -x tests/report/clover.xml -o tests/report/coveralls.json -v
